### ISSUE TITLE
make sections in each HTML file for custom js and css

### ISSUE THREAD

**Issue by jeffmjack** [jeffmjack/template-bootstrap#4]
this should go in tandem with figuring out out to do php-style includes for boilerplate head and script sections in all files

**Comment by jeffmjack** [comment]
@jhs Do you think it would be useful for me to start learning to use grep, xargs, and sed to this end? Is there an easier way? Is there decent payoff in developing proficiency in the above tools?

**Comment by jeffmjack** [comment]
[posterity][1]

[1]: http://erichogue.ca/2011/01/linux/search-and-replace-across-multiple-files-in-bash/

**Comment by jhs** [comment]
I'm not sure I understand what this issue subject means. What sections, what file?

**Comment by jeffmjack** [comment]
I was referring the partials thing that you addressed twice in #2 and #7 - I'm going to look into using gulp-template or gulp-mustache or sthg.
